#!/bin/sh
# SPDX-License-Identifier: MIT
set -eu

cargo fmt --all -- --check
cargo clippy --workspace --all-targets --locked -- -D warnings
cargo test --workspace --locked
cargo build --workspace --release --locked
